version: '3.8'

services:
    php:
        build: .
        container_name: symfony-php
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - redis
        environment:
            SYMFONY_ENV: dev

    nginx:
        image: nginx:latest
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    redis:
        image: redis:alpine
        container_name: symfony-redis
        ports:
            - "6379:6379"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
        volumes:
            - esdata:/usr/share/elasticsearch/data
